from django.contrib import admin
from django.urls import path
from .views import index_view,subcategory_view, services_view, login_view, signup_view, book_functionality_view
from .views import profile_view, complaint_view, manager_dashboard_view, serviceman_dashboard_view, servicemanlist_view
from .views import task_view,serviceman_task_view, logout_view, search_view, otp_view
from .views import forget_password_view,feedback_view, update_spareparts, pdf_view, ajax_view, rate_card_view

urlpatterns = [
    # Users URLS
    path('', index_view.indexfun, name="index"),
    path('subcategorypage/<int:cat_id>', subcategory_view.subcategorypage, name="subcategorypage"),
    path('servicepage/<int:subcat_id>', services_view.servicefun , name="service"),
    path('loginpage', login_view.loginpage, name="loginpage"),
    path('signuppage', signup_view.signuppage, name="signuppage"),
    path('booknowpage/<int:sid>', book_functionality_view.booknowpage, name="booknowpage"),
    path('insertbookingdata', book_functionality_view.insertbookingdata, name="insertbookingdata"),
    path('register', signup_view.register_fun, name="register"),
    path('checklogin_details', login_view.checklogin_details, name="checklogin_details"),
    path('user_logout', logout_view.user_logout_fun, name="user_logout"),
    path('bookingdone', book_functionality_view.bookingdone, name="bookingdone"),
    path('profile', profile_view.profilefun, name="profile"),
    path('mybookings/<str:status>', book_functionality_view.mybookingpage, name="mybookings"),
    path('bookingdetails/<int:booking_id>', book_functionality_view.bookingdetailsfun, name="bookingdetails"),
    path('submitcomplaint', complaint_view.savecomplaintfun, name="submitcomplaint"),
    path('update_uprofilepic', profile_view.updateprofilepic, name="update_uprofilepic"),
    path('changepassword', profile_view.changepasswordfun, name="changepassword"),
    path('cancelbooking/<int:bookingid>', book_functionality_view.cancelbookingfun, name="cancelbooking"),
    path('updateuserprofiledata', profile_view.updateuserprofiledata, name="updateuserprofiledata"),
    path('forgetpassword_page', forget_password_view.forgetpassword_page, name="forgetpassword_page"),
    path('forgetpassword_page2', forget_password_view.forgetpassword_page2, name="forgetpassword_page2"),
    path('regenerateotp/<str:email>', forget_password_view.regenerate_otp, name="regenerateotp"),
    path('forgetpassword', forget_password_view.forgetpassword_fun, name="forgetpassword"),
    path('forgetpass_otpverification', forget_password_view.forgetpass_otpverification_fun, name="forgetpass_otpverification"),
    path('check_forgetpass_details', forget_password_view.check_forgetpass_details, name="check_forgetpass_details"),
    path('feedback_page/<int:booking_id>', feedback_view.feedback_page, name="feedback_page"),
    path('submitfeedback', feedback_view.submit_feedback, name="submitfeedback"),
    path('sp_payment_summary/<int:task_id>', update_spareparts.sparepart_payment_summary_page, name="sp_payment_summary"),
    path('make_sparepart_payment', update_spareparts.make_payment_for_updated_sparepart,name="make_sparepart_payment"),
    path('rate_card/<int:subcat_id>', rate_card_view.rate_card, name="rate_card"),
    path('generate_invoice/<int:booking_id>', pdf_view.generate_invoice, name="generate_invoice"),

    # Manager Urls
    path('manager_logout', logout_view.manager_logout_fun, name="manager_logout"),
    path('manager_dashboard', manager_dashboard_view.manager_dashboard_page, name="manager_dashboard"),
    path('listofcategory', manager_dashboard_view.show_category_list_for_serviceman, name="listofcategory"),
    path('managerprofile', profile_view.manager_profilefun, name="managerprofile"),
    path('servicemanlistascategory', servicemanlist_view.fetch_servicemanlist, name="servicemanlistascategory"),
    path('getservicemanlst/<int:cat_id>', servicemanlist_view.fetch_servicemanlist_by_category, name="getservicemanlst"),
    path('task_list', task_view.task_list_fun, name="task_list"),
    path('tasks_of_selected_date', task_view.get_tasks_of_selected_date, name="tasks_of_selected_date"),
    path('retrieve_task/<int:task_id>', task_view.retrieve_task, name="retrieve_task"),
    path('listof_alltask_bydate/<str:DateTimeslot>', task_view.list_of_all_task_by_date, name="listof_alltask_bydate"),
    path('listof_pendingtask_bydate/<str:DateTimeslot>', task_view.list_of_pending_task_by_date, name="listof_pendingtask_bydate"),
    path('listof_allocatedtask_bydate/<str:DateTimeslot>', task_view.list_of_allocated_task_by_date, name="listof_allocatedtask_bydate"),
    path('listof_completedtask_bydate/<str:DateTimeslot>', task_view.list_of_completed_task_by_date, name="listof_completedtask_bydate"),
    path('listof_pickedtask_bydate/<str:DateTimeslot>', task_view.list_of_picked_task_by_date, name="listof_pickedtask_bydate"),
    path('listof_cancelledtask_bydate/<str:DateTimeslot>', task_view.list_of_cancelled_task_by_date, name="listof_cancelledtask_bydate"),
    path('listof_closedtask_bydate/<str:DateTimeslot>', task_view.list_of_closed_task_by_date, name="listof_closedtask_bydate"),
    path('fetch_serviceman_list_to_assigntask/<str:catid_task_id>', task_view.fetch_serviceman_list_to_assigntask, name="fetch_serviceman_list_to_assigntask"),
    path('assigntask_to_serviceman/<int:serviceman_id>/<int:task_id>', task_view.assign_task_to_serviceman, name="assigntask_to_serviceman"),
    path('fetchdate/<str:date>', task_view.fetchdate, name="fetchdate"),
    path('searchservice_result', search_view.search_service_result_fun, name="searchservice_result"),
    path('listofservicemantasks/<int:s_id>', task_view.list_of_servicemantask_page, name="listofservicemantasks"),
    path('fetch_serviceman_tasklist_by_date', task_view.fetch_serviceman_tasklist_by_date, name="fetch_serviceman_tasklist_by_date"),
    path('fetch_serviceman_tasklist_by_month', task_view.fetch_serviceman_tasklist_by_month, name="fetch_serviceman_tasklist_by_month"),
    path('fetch_list_of_all_task_by_date', task_view.fetch_list_of_all_task_by_date, name="fetch_list_of_all_task_by_date"),
    path("list_of_all_task", task_view.list_of_all_task_page,name="list_of_all_task"),
    path('fetch_list_of_all_task_by_month', task_view.fetch_list_of_all_task_by_month,name="fetch_list_of_all_task_by_month"),
    path('searchserviceman_result', search_view.search_serviceman_result_fun,name='searchserviceman_result'),
    path('generate_report_by_date', pdf_view.generate_report_by_date, name='generate_report_by_date'),
    path('generate_report_by_month', pdf_view.generate_report_by_month, name='generate_report_by_month'),
    path('generate_report_by_year', pdf_view.generate_report_by_year, name='generate_report_by_year'),
    path('view_serviceman_profile/<int:serviceman_id>', profile_view.view_serviceman_profile_by_manager, name='view_serviceman_profile'),

    # Serviceman Urls
    path('serviceman_dashboard', serviceman_dashboard_view.serviceman_dashboard_page, name="serviceman_dashboard"),
    path('serviceman_logout', logout_view.serviceman_logout_fun, name="serviceman_logout"),
    path('serviceman_profile', profile_view.serviceman_profile_fun, name="serviceman_profile"),
    path('allocated_task', serviceman_task_view.allocated_task_fun, name="allocated_task"),
    path('picked_task', serviceman_task_view.picked_task_fun, name="picked_task"),
    path('accept_task/<int:task_id>', serviceman_task_view.accept_task_fun, name="accept_task"),
    # path('start_work/<str:task_id>', serviceman_task_view.start_work_fun, name="start_work"),
    # path('complete_work/<int:task_id>', serviceman_task_view.complete_work_fun, name="complete_work"),
    # path('close_task/<int:task_id>', serviceman_task_view.close_task_fun, name="close_task"),
    path('today_task', serviceman_task_view.allocated_task_fun, name="today_task"),
    path('task_history', serviceman_task_view.task_history_fun, name="task_history"),
    path('completed_task', serviceman_task_view.completed_task_fun, name="competed_task"),
    path('datefilter', serviceman_task_view.get_task_by_date, name="datefilter"),
    path('monthyearfilter', serviceman_task_view.get_task_by_month, name="monthyearfilter"),
    path('generate_otp/<int:task_id>', otp_view.send_otp, name="generate_otp"),
    path('generate_otp_for_closetask/<int:task_id>', otp_view.send_otp_for_closetask, name="generate_otp_for_closetask"),
    path('startwork_verify_otp', otp_view.startwork_verify_otp_fun, name="startwork_verify_otp"),
    path('completework_verify_otp', otp_view.completework_verify_otp_fun, name="completework_verify_otp"),
    path('closetask_verify_otp', otp_view.closetask_verify_otp_fun, name="closetask_verify_otp"),
    path('updatespareparts_page/<int:task_id>', update_spareparts.update_spareparts_page, name="updatespareparts_page"),
    path('fetch_sparepartname_list', update_spareparts.fetch_sparepartname_list, name="fetch_sparepartname_list"),
    path('update_name', update_spareparts.update_sparepart, name="update_name"),
    path('updated_sp', update_spareparts.updated_sparepartname, name="updated_sp"),
    path('view_updated_sp/<int:task_id>', update_spareparts.updated_sparepartname, name="view_updated_sp"),
    path('remove_sp/<str:spid_taskid>', update_spareparts.remove_sparepart, name="view_updated_sp"),
    path('updatepayment/<int:task_id>', update_spareparts.update_payment_to_user, name="updatepayment"),
    path('fetch_sparepart/<int:sptitle_id>/<int:task_id>', ajax_view.fetch_spareparts, name="fetch_sparepart"),
]