# Generated by Django 5.0.2 on 2024-02-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=256)),
                ('card_number', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
                ('catimage', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_email', models.EmailField(max_length=254)),
                ('m_password', models.CharField(max_length=256)),
                ('m_name', models.CharField(max_length=100)),
                ('m_phoneno', models.BigIntegerField()),
                ('sm_work_experience', models.CharField(max_length=20)),
                ('m_age', models.IntegerField()),
                ('m_address', models.TextField()),
                ('m_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=10)),
                ('m_profile_pic', models.ImageField(upload_to='manager')),
                ('m_adharno', models.BigIntegerField()),
                ('m_adharphoto', models.ImageField(upload_to='manager')),
                ('m_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_password', models.CharField(max_length=256)),
                ('u_fname', models.CharField(max_length=50)),
                ('u_lname', models.CharField(max_length=50)),
                ('u_phoneno', models.BigIntegerField()),
                ('u_address', models.TextField(null=True)),
                ('u_area', models.CharField(max_length=30, null=True)),
                ('u_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=10, null=True)),
                ('u_profilepic', models.ImageField(null=True, upload_to='user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sprice', models.IntegerField()),
                ('sdescription', models.TextField()),
                ('simage', models.ImageField(upload_to='photos')),
                ('scatname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.category')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date_time', models.DateTimeField()),
                ('booking_provide_date', models.DateField()),
                ('booking_provide_time', models.TimeField()),
                ('booking_address', models.TextField()),
                ('booking_area', models.CharField(max_length=30)),
                ('booking_status', models.CharField(max_length=30)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_email', models.EmailField(max_length=254)),
                ('sm_password', models.CharField(max_length=256)),
                ('sm_name', models.CharField(max_length=100)),
                ('sm_phoneno', models.BigIntegerField()),
                ('sm_age', models.IntegerField()),
                ('sm_address', models.TextField()),
                ('sm_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=10)),
                ('sm_knowledge_of_work', models.CharField(max_length=50)),
                ('sm_work_experience', models.CharField(max_length=20)),
                ('sm_profile_pic', models.ImageField(upload_to='serviceman')),
                ('sm_adharno', models.BigIntegerField()),
                ('sm_adharphoto', models.ImageField(upload_to='serviceman')),
                ('sm_status', models.CharField(max_length=50)),
                ('sm_salary', models.IntegerField()),
                ('sm_Knowledge_of_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.category')),
            ],
        ),
        migrations.CreateModel(
            name='Spareparttitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_title', models.CharField(max_length=30)),
                ('sp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepart_name', models.CharField(max_length=100)),
                ('sparepart_price', models.IntegerField()),
                ('sparepart_quantity', models.IntegerField()),
                ('sparepart_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.spareparttitle')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatname', models.CharField(max_length=20)),
                ('subcatimage', models.ImageField(upload_to='photos')),
                ('catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.category')),
            ],
        ),
        migrations.AddField(
            model_name='spareparttitle',
            name='sp_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.subcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='ssubcatname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.subcategory'),
        ),
        migrations.CreateModel(
            name='Sparepart_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepart_amount', models.IntegerField()),
                ('sparepart_tax', models.FloatField()),
                ('sparepart_total_amount', models.FloatField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.carddetails')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service')),
                ('serviceman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service_man')),
                ('sparepart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.sparepart')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('tax', models.FloatField()),
                ('totalamount', models.FloatField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.carddetails')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback_title', models.CharField(max_length=100)),
                ('feedback_description', models.TextField()),
                ('feedback_datetime', models.DateTimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateTimeField()),
                ('complaint_topic', models.CharField(max_length=100)),
                ('complaint_pic', models.ImageField(upload_to='complaints')),
                ('complaint_description', models.TextField()),
                ('complaint_status', models.CharField(choices=[('1', 'Pending'), ('2', 'solved')], max_length=30)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user')),
            ],
        ),
        migrations.AddField(
            model_name='carddetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user'),
        ),
    ]
