# Generated by Django 5.0.2 on 2024-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catimage',
            field=models.ImageField(upload_to='media/category'),
        ),
    ]
