# Generated by Django 5.0.2 on 2024-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0002_alter_category_catimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catimage',
            field=models.ImageField(upload_to='category'),
        ),
    ]
