# Generated by Django 5.0.2 on 2024-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0005_booking_data_alter_complaint_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
