# Generated by Django 5.0.2 on 2024-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0006_alter_user_u_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_data',
            name='booking_provide_time',
            field=models.CharField(max_length=10),
        ),
    ]
