# Generated by Django 5.0.2 on 2024-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0008_alter_complaint_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
