# Generated by Django 5.0.2 on 2024-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0009_alter_complaint_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='instaff',
            field=models.BooleanField(default=True),
        ),
    ]
