# Generated by Django 5.0.2 on 2024-02-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0014_booking_alter_complaint_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='m_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Serviceman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_email', models.EmailField(max_length=254)),
                ('sm_password', models.CharField(max_length=256)),
                ('sm_name', models.CharField(max_length=100)),
                ('sm_phoneno', models.BigIntegerField()),
                ('sm_age', models.IntegerField()),
                ('sm_address', models.TextField()),
                ('sm_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=10)),
                ('sm_knowledge_of_work', models.CharField(max_length=50)),
                ('sm_work_experience', models.CharField(max_length=20)),
                ('sm_profile_pic', models.ImageField(upload_to='serviceman')),
                ('sm_adharno', models.BigIntegerField()),
                ('sm_adharphoto', models.ImageField(upload_to='serviceman')),
                ('sm_status', models.CharField(max_length=50)),
                ('sm_salary', models.IntegerField()),
                ('sm_d_o_j', models.DateField()),
                ('sm_d_o_l', models.DateField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_logout_time', models.DateTimeField(blank=True, null=True)),
                ('instaff', models.BooleanField(default=True)),
                ('sm_Knowledge_of_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.category')),
            ],
        ),
        migrations.AlterField(
            model_name='sparepart_payment',
            name='serviceman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.serviceman'),
        ),
        migrations.DeleteModel(
            name='Service_man',
        ),
    ]
