# Generated by Django 5.0.2 on 2024-02-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0015_alter_manager_m_gender_serviceman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upi_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=50)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
            ],
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.upi_details'),
        ),
        migrations.AlterField(
            model_name='sparepart_payment',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.upi_details'),
        ),
        migrations.DeleteModel(
            name='Carddetails',
        ),
    ]
