# Generated by Django 5.0.2 on 2024-02-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0016_upi_details_alter_paymentdetails_card_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
                ('pick_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('close_task', models.DateTimeField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
                ('serviceman_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HCH.serviceman')),
            ],
        ),
    ]
