# Generated by Django 5.0.2 on 2024-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0017_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='card_id',
            new_name='upi_id',
        ),
        migrations.RenameField(
            model_name='sparepart_payment',
            old_name='card_id',
            new_name='upi_id',
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='sm_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
