# Generated by Django 5.0.2 on 2024-02-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0018_rename_card_id_paymentdetails_upi_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sparepart_payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepart_amount', models.IntegerField()),
                ('sparepart_tax', models.FloatField()),
                ('sparepart_total_amount', models.FloatField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.booking')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.service')),
                ('serviceman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.serviceman')),
                ('sparepart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.sparepart')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.task')),
                ('upi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.upi_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCH.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Sparepart_payment',
        ),
    ]
