# Generated by Django 5.0.2 on 2024-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0019_sparepart_payment_details_delete_sparepart_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sparepart_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
