# Generated by Django 5.0.2 on 2024-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0020_user_active_alter_sparepart_sparepart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='need_sparepart',
            field=models.BooleanField(default=False),
        ),
    ]
