# Generated by Django 5.0.2 on 2024-03-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0022_updated_sparepart_sparepart_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart_payment',
            name='sparepart_amount',
        ),
    ]
