# Generated by Django 5.0.2 on 2024-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0023_remove_sparepart_payment_sparepart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='upi_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sparepart_payment',
            name='upi_id',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Upi_details',
        ),
    ]
