# Generated by Django 5.0.2 on 2024-03-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0024_alter_paymentdetails_upi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updated_sparepart',
            name='sparepart_ids',
        ),
        migrations.AddField(
            model_name='updated_sparepart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updated_sparepart',
            name='sparepart_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HCH.sparepart'),
            preserve_default=False,
        ),
    ]
