# Generated by Django 5.0.2 on 2024-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0025_remove_updated_sparepart_sparepart_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart_payment',
            name='updated_spareparts',
        ),
        migrations.AddField(
            model_name='sparepart_payment',
            name='updated_spareparts',
            field=models.ManyToManyField(to='HCH.updated_sparepart'),
        ),
    ]
