# Generated by Django 5.0.2 on 2024-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0026_remove_sparepart_payment_updated_spareparts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparttitle',
            name='sp_title',
            field=models.CharField(max_length=256),
        ),
    ]
