# Generated by Django 5.0.2 on 2024-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0027_alter_spareparttitle_sp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updated_sparepart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
