# Generated by Django 5.0.2 on 2024-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0028_alter_updated_sparepart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_provide_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcatname',
            field=models.CharField(max_length=256),
        ),
    ]
