# Generated by Django 5.0.2 on 2024-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0029_alter_booking_booking_provide_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updated_sparepart',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
