# Generated by Django 5.0.2 on 2024-04-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HCH', '0031_sparepart_payment_sparepart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='other',
        ),
    ]
